name: Deploy Docs from dev-fara2

on:
  push:
    branches:
      - main  # Workflow runs only when main is pushed

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev-fara2 branch
        uses: actions/checkout@v3
        with:
          ref: dev-fara2  # Pull content from this branch

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Copy prebuilt HTML docs into publish folder
        run: |
          mkdir -p publish/backend
          mkdir -p publish/frontend
          cp -r BackEnd/docs/* publish/backend/
          cp -r FrontEnd/documentation/* publish/frontend/

      - name: Create index.html with links to both docs
        run: |
          cat <<EOF > publish/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Documentation Portal</title>
          </head>
          <body>
            <h1>Project Documentation</h1>
            <ul>
              <li><a href="./frontend/">Frontend Documentation (Compodoc)</a></li>
              <li><a href="./backend/">Backend Documentation (Sphinx)</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./publish
