name: Deploy Front End documentation to GitHub Pages

on:
  push:
    branches: ["dev-fara2"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev-fara2 

      # Step 2: Set up the Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Only upload the documentation folder inside the FrontEnd folder
          path: './FrontEnd/documentation' 

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
