name: Deploy Docs

on:
  push:
    branches: ["dev-fara2"]  # Trigger on push to dev-fara2
  workflow_dispatch:         # Allow manual trigger from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev-fara2 branch
        uses: actions/checkout@v4
        with:
          ref: dev-fara2

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Prepare documentation folders
        run: |
          mkdir -p publish/frontend
          mkdir -p publish/backend
          cp -r FrontEnd/documentation/* publish/frontend/
          cp -r BackEnd/docs/* publish/backend/

      - name: Create index.html with links
        run: |
          cat <<EOF > publish/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Project Documentation</title>
          </head>
          <body>
            <h1>Project Documentation</h1>
            <ul>
              <li><a href="./frontend/">Frontend Documentation (Compodoc)</a></li>
              <li><a href="./backend/">Backend Documentation (Sphinx)</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./publish

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
